// Code generated by scripts/generate-release-policy.py; DO NOT EDIT.

package egobrowserartifact

const (
	// PinnedWrapperVersion identifies the reviewed Linux ego-browser wrapper release.
	PinnedWrapperVersion = "0.1.18"
	// PinnedProtocolVersion identifies the reviewed ego-browser protocol.
	PinnedProtocolVersion = "ego-browser-bridge-v1"
	// OfficialSkillName identifies the reviewed upstream Skill name.
	OfficialSkillName = "ego-browser"
	// OfficialSkillVersion identifies the reviewed upstream ego-browser Skill release.
	OfficialSkillVersion = "2.0.0"
	// OfficialSkillUpstreamRepository identifies the reviewed upstream Skill repository.
	OfficialSkillUpstreamRepository = "https://github.com/citrolabs/ego-lite"
	// OfficialSkillSourceCommit identifies the reviewed upstream ego-lite tree.
	OfficialSkillSourceCommit = "d01be93325c7ea59d41c2ca9f4c59b58b4be4046"
	// OfficialSkillDocumentSHA256 identifies the reviewed upstream SKILL.md bytes.
	OfficialSkillDocumentSHA256 = "9402bf03db895209a755d5e2af9b436dbf98eed0911907110a4ea482c30632de"
	// OfficialSkillTreeSHA256 identifies the reviewed upstream Skill tree.
	OfficialSkillTreeSHA256 = "a45cc7fcbea45a6f6222faf83c891b0fd22955193699dd99c9e40b0c0b4a0741"
)
