// Code generated by scripts/generate-release-policy.py; DO NOT EDIT.

package egobrowserartifact

const (
	// PinnedWrapperVersion identifies the reviewed Linux ego-browser wrapper release.
	PinnedWrapperVersion = "0.1.12"
	// PinnedProtocolVersion identifies the reviewed ego-browser protocol.
	PinnedProtocolVersion = "ego-browser-bridge-v1"
	// OfficialSkillName identifies the reviewed upstream Skill name.
	OfficialSkillName = "ego-browser"
	// OfficialSkillVersion identifies the reviewed upstream ego-browser Skill release.
	OfficialSkillVersion = "1.2.3"
	// OfficialSkillUpstreamRepository identifies the reviewed upstream Skill repository.
	OfficialSkillUpstreamRepository = "https://github.com/citrolabs/ego-lite"
	// OfficialSkillSourceCommit identifies the reviewed upstream ego-lite tree.
	OfficialSkillSourceCommit = "36053d07001a910cb806a15d42d00fdea1cdea3d"
	// OfficialSkillDocumentSHA256 identifies the reviewed upstream SKILL.md bytes.
	OfficialSkillDocumentSHA256 = "44c119634df847861486c3b104cda3c2faa9dd4c71dbb3a854429098be962293"
	// OfficialSkillTreeSHA256 identifies the reviewed upstream Skill tree.
	OfficialSkillTreeSHA256 = "262110a09678fd3e0bbb382400588dacb98b24659b3b4a57903703b65d133c7c"
)
